services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mis-container
    ports:
      - "8001:8000"
    depends_on:
      - db
    command: "./mis"

  db:
    image: postgres:16.0
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mis
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_data: